
 --BORRADOR previo a la convención de nombres

--Tablas modeladas en el DER

CREATE SCHEMA ESTRUCTURAL
GO

CREATE TABLE ESTRUCTURAL.UNIDAD_FUNCIONAL(
	Nro_Edificio INT NOT NULL,
	Nro_Unidad INT NOT NULL,
	Piso_Depto VARCHAR(255) NOT NULL,
	Costo DECIMAL(10,2) NOT NULL,
	Superficie DECIMAL(5,2) NOT NULL,
	Mail VARCHAR(255) NOT NULL
	CONSTRAINT PK_Unidad_Funcional PRIMARY KEY (Nro_Edificio, Nro_Unidad)
)	
GO

CREATE TABLE ESTRUCTURAL.PROPIETARIO(
	CUIT CHAR(13) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(255) NOT NULL,
	Teléfono NUMBER,
	Domicilio VARCHAR(255) NOT NULL,
	Nro_Unidad INT NOT NULL,
	CONSTRAINT FK_Unidad_Funcional REFERENCES ESTRUCTURAL.UNIDAD_FUNCIONAL(Nro_Unidad)
)
GO

CREATE TABLE ESTRUCTURAL.INQUILINO(
	CUIT CHAR(13) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(255) NOT NULL,
	Teléfono NUMBER,
	Domicilio VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	Nro_Unidad INT NOT NULL,
	CONSTRAINT FK_Unidad_Funcional REFERENCES ESTRUCTURAL.UNIDAD_FUNCIONAL(Nro_Unidad)
)
GO

CREATE TABLE ESTRUCTURAL.EDIFICIO(
	Nro_Edificio INT PRIMARY KEY,
	Dirección VARCHAR(255) NOT NULL,
	Superficie DECIMAL(8,2) NOT NULL,
	Cant_Unidad_Func INT NOT NULL,
	ID_Cuenta INT NOT NULL
)
GO

CREATE TABLE ESTRUCTURAL.CUENTA_BANCARIA_ASOCIADA(
	ID_Cuenta INT PRIMARY KEY,
	CUIT CHAR(13) NOT NULL,
	Tipo CHAR(3) CHECK (Tipo IN ('CBU', 'CVU')) NOT NULL,
	Número CHAR(22) NOT NULL
)
GO

CREATE TABLE ESTRUCTURAL.CUENTA_BANCARIA_CONSORCIO(
	ID_Cuenta INT PRIMARY KEY,
	Razon_Social VARCHAR(13) NOT NULL,
	Tipo CHAR(3) CHECK (Tipo IN ('CBU', 'CVU')) NOT NULL,
	Número CHAR(22) NOT NULL
)
GO

CREATE TABLE ESTRUCTURAL.CONSORCIO(
	CUIT CHAR(13) PRIMARY KEY,
	Razon_Social VARCHAR(255) NOT NULL,
	Domicilio VARCHAR(255) NOT NULL,
	Nro_Edificio INT CONSTRAINT FK_Edificio REFERENCES ESTRUCTURAL.EDIFICIO(Nro_Edificio)
)
GO

CREATE TABLE ESTRUCTURAL.BALANCE_FINANCIERO(
	CUIT CHAR(13) CONSTRAINT FK_Consorcio REFERENCES ESTRUCTURAL.CONSORCIO(CIUT),
	Perido VARCHAR(255) NOT NULL,
	Saldo_Anterior DECIMAL(10,2) CHECK(Saldo_Anterior >= 0) NOT NULL
)

CREATE TABLE ESTRUCTURAL.COCHERA(
	Nro_Cochera INT PRIMARY KEY,
	Nro_Unidad INT CONSTRAINT FK_Unidad_Funcional REFERENCES ESTRUCTURAL.UNIDAD_FUNCIONAL(Nro_Unidad),
	Costo DECIMAL (10,2) CHECK(Costo >= 0)

)
GO

CREATE TABLE ESTRUCTURAL.BAULERA(
	Nro_Cochera INT PRIMARY KEY,
	Nro_Unidad INT CONSTRAINT FK_Unidad_Funcional REFERENCES EDILICIO.UNIDAD_FUNCIONAL(Nro_Unidad)
	Costo DECIMAL (10,2) CHECK(Costo >= 0)
)
GO

-- BORRADOR MAESTROS

CREATE TABLE ESTRUCTURAL.PROPIETARIO(
	DNI INT NOT NULL PRIMARY KEY,
	Nombre VARCHAR(255) NOT NULL,
	Apellido VARCHAR(255),
	Teléfono NUMBER,
	Domicilio VARCHAR(255) NOT NULL,
	Nro_Unidad INT NOT NULL,
	Email VARCHAR(255) NOT NULL,
	EsInquilino BOOLEAN NOT NULL,
	CONSTRAINT FK_Unidad_Funcional REFERENCES ESTRUCTURAL.UNIDAD_FUNCIONAL(Nro_Unidad)
)
GO

CREATE TABLE ESTRUCTURAL.INQUILINO(
	DNI INT NOT NULL PRIMARY KEY,
	Nombre VARCHAR(255) NOT NULL,
	Apellido VARCHAR(255),
	Teléfono NUMBER,
	Domicilio VARCHAR(255) NOT NULL,
	Nro_Unidad INT NOT NULL,
	Email VARCHAR(255) NOT NULL,
	EsInquilino BOOLEAN NOT NULL,
	CONSTRAINT FK_Unidad_Funcional REFERENCES ESTRUCTURAL.UNIDAD_FUNCIONAL(Nro_Unidad)
)
GO

CREATE TABLE ESTRUCTURAL.CUENTA_BANCARIA_ASOCIADA(
	ID_Cuenta INT PRIMARY KEY,
	DNI INT NOT NULL,
	Número CHAR(22) NOT NULL
)
GO

CREATE SCHEMA ADMINISTRATIVO
GO

CREATE TABLE ADMINISTRATIVO.LIQUIDACIÓN(
	Id_Liquidación INT IDENTITY(1,1) PRIMARY KEY,
	Nro_Edificio INT CONSTRAINT FK_Edificio REFERENCES ESTRUCTURAL.EDIFICIO(Nro_Edificio),
	Id_Gasto_Extraordinario INT CONSTRAINT FK_Gasto_Extraord REFERENCES ADMINISTRATIVO.GASTO_EXTRAORD(Id_Gasto_Extraordinario),
	Id_Gasto_Ordinario INT CONSTRAINT FK_Gasto_Ord REFERENCES ADMINISTRATIVO.GASTO_ORDINARIO(Id_Gasto_Ordinario),
	Importe_Total DECIMAL(10,2) CHECK(Importe_Total >= 0) NOT NULL,
	Fecha_Emision DATE NOT NULL,
	Periodo VARCHAR(255) NOT NULL,
	Fecha_Venc_1 DATE NOT NULL,
	Fecha_Venc_2 DATE NOT NULL,
	Porcentaje_Interés DECIMAL(10,2) CHECK(Porcentaje_Interés >= 0) NOT NULL,
	Estado VARCHAR CHECK(Estado IN('Abierta', 'Cerrada')) NOT NULL,
	Esta_Paga BOOLEAN NOT NULL
)
GO

CREATE TABLE ADMINISTRATIVO.GASTO_EXTRAORD(
	Id_Gasto_Extraordinario INT IDENTITY(1,1) PRIMARY KEY,
	Importe_Total DECIMAL(10,2) CHECK(Importe_Total >= 0) NOT NULL,
	Detalle VARCHAR(255) NOT NULL,
	Tipo VARCHAR(255) CHECK(Tipo IN ('Reparación', 'Construcción')) NOT NULL,
	Modo_Pago VARCHAR(255) CHECK(Tipo IN ('Pago Total', 'Pago en Cuotas')) NOT NULL,
)
GO

CREATE TABLE ADMINISTRATIVO.GASTO_ORDINARIO(
	Id_Gasto_Ordinario INT IDENTITY(1,1) PRIMARY KEY,
	Tipo VARCHAR(255) CHECK(Tipo IN ('Seguro','General','Limpieza', 'Servicio Público', 'Administrativo', 'Cuenta Bancaria')) NOT NULL,
	Nro_Factura INT NOT NULL,
	Importe DECIMAL(10,2) NOT NULL,
	Razon_Social VARCHAR(255) NOT NULL,
	Fecha DATE NOT NULL,
	Detalle VARCHAR(255)
)
GO

CREATE TABLE ADMINISTRATIVO.LIMPIEZA_OPC_1(
	Id_Gasto_Ordinario INT CONSTRAINT FK_Gasto_Ordinario REFERENCES ADMINISTRATIVO.GASTO_ORDINARIO(Id_Gasto_Ordinario),
	Sueldo DECIMAL(10,2) CHECK(Sueldo >= 0),
	Factura VARCHAR(255) NOT NULL
)
GO

CREATE TABLE ADMINISTRATIVO.LIMPIEZA_OPC_2(
	Id_Gasto_Ordinario INT CONSTRAINT FK_Gasto_Ordinario REFERENCES ADMINISTRATIVO.GASTO_ORDINARIO(Id_Gasto_Ordinario),
	Nro_Factura INT NOT NULL,
	Razon_Social VARCHAR(255) NOT NULL,
	Importe DECIMAL(10,2) CHECK(Importe >= 0) NOT NULL
)
GO

CREATE TABLE ADMINISTRATIVO.SERVICIO_PUBLICO(
	Id_Gasto_Ordinario INT CONSTRAINT FK_Gasto_Ordinario REFERENCES ADMINISTRATIVO.GASTO_ORDINARIO(Id_Gasto_Ordinario),
	Tipo VARCHAR(255) CHECK(Tipo IN ('Luz', 'Agua', 'Internet'))
)
GO

CREATE TABLE ADMINISTRATIVO.PAGO_TOTAL(
	Id_Gasto_Extraordinario INT CONSTRAINT FK_Gasto_Extraord REFERENCES ADMINISTRATIVO.GASTO_EXTRAORD(Id_Gasto_Extraordinario),
	Pagado BOOLEAN NOT NULL,
	Fecha DATE NOT NULL
)
GO

CREATE TABLE ADMINISTRATIVO.PAGO_EN_CUOTAS(
	Id_Gasto_Extraordinario INT CONSTRAINT FK_Gasto_Extraord REFERENCES ADMINISTRATIVO.GASTO_EXTRAORD(Id_Gasto_Extraordinario),
	Cant_Coutas INT,
	Importe_Cuota DECIMAL(10,2) CHECK(Importe_Cuota >= 0)
)
GO

CREATE TABLE ADMINISTRTIVO.CUOTA_PAGADA(
	Id_Cuota INT IDENTITY(1,1) PRIMARY KEY,
	Id_Gasto_Extraordinario INT CONSTRAINT FK_Gasto_Extraord REFERENCES ADMINISTRATIVO.GASTO_EXTRAORD(Id_Gasto_Extraordinario),
	Nro_Cuota INT,
	Fecha_Pago DATE
)
GO

CREATE TABLE ADMINISTRATIVO.EXPENSA_POR_UNIDAD(
	Id_Expensa_Unidad INT IDENTITY(1,1) PRIMARY KEY,
	Id_Liquidación INT CONSTRAINT FK_Liquidación REFERENCES ADMINISTRATIVO.LIQUIDACIÓN(Id_Liquidación),
	Nro_Unidad INT CONSTRAINT FK_Unidad_Funcional REFERENCES ESTRUCTURAL.UNIDAD_FUNCIONAL(Nro_Unidad),
	Porcentaje_Prorrateo DECIMAL(10,2) CHECK(Porcentaje_Prorrateo >= 0) NOT NULL,
	Saldo_Anterior DECIMAL(10,2) CHECK(Saldo_Anterior >= 0) NOT NULL,
	Importe DECIMAL(10,2) CHECK(Importe >= 0) NOT NULL,
	Fecha_Emision DATE NOT NULL
)
GO

CREATE TABLE ADMINISTRATIVO.DOCUMENTO_EXPENSA(
	Id_Documento INT IDENTITY(1,1) PRIMARY KEY,
	Id_Expensa_Unidad INT CONSTRAINT FK_Expensa_Por_Unidad REFERENCES ADMINISTRATIVO.EXPENSA_POR_UNIDAD(Id_Expensa_Unidad),
	Modo_Entrega VARCHAR() CHECK(Modo_Entrega IN ('Impreso', 'Email', 'Whatsapp'))
)
GO


CREATE TABLE ADMINISTRATIVO.PAGO(
	Id_Pago INT IDENTITY(1,1) PRIMARY KEY,
	Id_Liquidación INT CONSTRAINT FK_Liquidación REFERENCES ADMINISTRATIVO.LIQUIDACIÓN(Id_Liquidación),
	Fecha_Pago DATE NOT NULL,
	Importe DECIMAL(10,2) NOT NULL,
	Nro_Cuenta CHAR(22) NOT NULL,
	Esta_Asociado BOOLEAN NOT NULL
)
GO

CREATE TABLE ADMINSTRATIVO.ESTADO_CUENTA_Y_PRORRATEO(
	Nro_Unidad INT CONSTRAINT FK_Unidad_Funcional REFERENCES ESTRUCTURAL.UNIDAD_FUNCIONAL(Nro_Unidad),
	Razon_Social VARCHAR(255) NOT NULL,
	Piso_Depto VARCHAR(255) NOT NULL,
	Porcentaje DECIMAL(10,2) CHECK(Porcentaje >= 0) NOT NULL,
	Nro_Cochera INT CONSTRAINT FK_Cochera REFERENCES ESTRUCTURAL.COCHERA(Nro_Cochera),
	Nro_Baulera INT CONSTRAINT FK_Bauleraa REFERENCES ESTRUCTURAL.BAULERA(Nro_Baulera)
)
GO