
 --BORRADOR previo a la convención de nombres

--Tablas modeladas en el DER

CREATE SCHEMA ESTRUCTURAL
GO

CREATE TABLE ESTRUCTURAL.UNIDAD_FUNCIONAL(
	Nro_Edificio INT NOT NULL,
	Nro_Unidad INT NOT NULL,
	Piso_Depto VARCHAR(255) NOT NULL,
	Costo DECIMAL(10,2) NOT NULL,
	Superficie DECIMAL(5,2) NOT NULL,
	Mail VARCHAR(255) NOT NULL
	CONSTRAINT PK_Unidad_Funcional PRIMARY KEY (Nro_Edificio, Nro_Unidad)
)	
GO

CREATE TABLE ESTRUCTURAL.PROPIETARIO(
	CUIT CHAR(13) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(255) NOT NULL,
	Teléfono NUMBER,
	Domicilio VARCHAR(255) NOT NULL,
	Nro_Unidad INT NOT NULL,
	CONSTRAINT FK_Unidad_Funcional REFERENCES ESTRUCTURAL.UNIDAD_FUNCIONAL(Nro_Unidad)
)
GO

CREATE TABLE ESTRUCTURAL.INQUILINO(
	CUIT CHAR(13) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(255) NOT NULL,
	Teléfono NUMBER,
	Domicilio VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	Nro_Unidad INT NOT NULL,
	CONSTRAINT FK_Unidad_Funcional REFERENCES ESTRUCTURAL.UNIDAD_FUNCIONAL(Nro_Unidad)
)
GO

CREATE TABLE ESTRUCTURAL.EDIFICIO(
	Nro_Edificio INT PRIMARY KEY,
	Dirección VARCHAR(255) NOT NULL,
	Superficie DECIMAL(8,2) NOT NULL,
	Cant_Unidad_Func INT NOT NULL,
	ID_Cuenta INT NOT NULL
)
GO

CREATE TABLE ESTRUCTURAL.CUENTA_BANCARIA_ASOCIADA(
	ID_Cuenta INT PRIMARY KEY,
	CUIT CHAR(13) NOT NULL,
	Tipo CHAR(3) CHECK (Tipo IN ('CBU', 'CVU')) NOT NULL,
	Número CHAR(22) NOT NULL
)
GO

CREATE TABLE ESTRUCTURAL.CUENTA_BANCARIA_CONSORCIO(
	ID_Cuenta INT PRIMARY KEY,
	Razon_Social VARCHAR(13) NOT NULL,
	Tipo CHAR(3) CHECK (Tipo IN ('CBU', 'CVU')) NOT NULL,
	Número CHAR(22) NOT NULL
)
GO

CREATE TABLE ESTRUCTURAL.CONSORCIO(
	CUIT CHAR(13) PRIMARY KEY,
	Razon_Social VARCHAR(255) NOT NULL,
	Domicilio VARCHAR(255) NOT NULL,
	Nro_Edificio INT CONSTRAINT FK_Edificio REFERENCES ESTRUCTURAL.EDIFICIO(Nro_Edificio)
)
GO

CREATE TABLE ESTRUCTURAL.BALANCE_FINANCIERO(
	CUIT CHAR(13) CONSTRAINT FK_Consorcio REFERENCES ESTRUCTURAL.CONSORCIO(CIUT),
	Perido VARCHAR(255) NOT NULL,
	Saldo_Anterior DECIMAL(10,2) CHECK(Saldo_Anterior >= 0) NOT NULL
)

CREATE TABLE ESTRUCTURAL.COCHERA(
	Nro_Cochera INT PRIMARY KEY,
	Nro_Unidad INT CONSTRAINT FK_Unidad_Funcional REFERENCES ESTRUCTURAL.UNIDAD_FUNCIONAL(Nro_Unidad),
	Costo DECIMAL (10,2) CHECK(Costo >= 0)

)
GO

CREATE TABLE ESTRUCTURAL.BAULERA(
	Nro_Cochera INT PRIMARY KEY,
	Nro_Unidad INT CONSTRAINT FK_Unidad_Funcional REFERENCES EDILICIO.UNIDAD_FUNCIONAL(Nro_Unidad)
	Costo DECIMAL (10,2) CHECK(Costo >= 0)
)
GO

-- BORRADOR MAESTROS

CREATE TABLE ESTRUCTURAL.PROPIETARIO(
	DNI INT NOT NULL PRIMARY KEY,
	Nombre VARCHAR(255) NOT NULL,
	Apellido VARCHAR(255),
	Teléfono NUMBER,
	Domicilio VARCHAR(255) NOT NULL,
	Nro_Unidad INT NOT NULL,
	Email VARCHAR(255) NOT NULL,
	EsInquilino BOOLEAN NOT NULL,
	CONSTRAINT FK_Unidad_Funcional REFERENCES ESTRUCTURAL.UNIDAD_FUNCIONAL(Nro_Unidad)
)
GO

CREATE TABLE ESTRUCTURAL.INQUILINO(
	DNI INT NOT NULL PRIMARY KEY,
	Nombre VARCHAR(255) NOT NULL,
	Apellido VARCHAR(255),
	Teléfono NUMBER,
	Domicilio VARCHAR(255) NOT NULL,
	Nro_Unidad INT NOT NULL,
	Email VARCHAR(255) NOT NULL,
	EsInquilino BOOLEAN NOT NULL,
	CONSTRAINT FK_Unidad_Funcional REFERENCES ESTRUCTURAL.UNIDAD_FUNCIONAL(Nro_Unidad)
)
GO

CREATE TABLE ESTRUCTURAL.CUENTA_BANCARIA_ASOCIADA(
	ID_Cuenta INT PRIMARY KEY,
	DNI INT NOT NULL,
	Número CHAR(22) NOT NULL
)
GO